export enum ORDER_STATUS {
    PENDING_REVIEW = 'PENDING_REVIEW',
    OUTSTANDING = 'OUTSTANDING',
    CONFIRMED_BY_SYSTEM = 'CONFIRMED BY SYSTEM',
    CANCELED_DUE_TO_PAYMENT = 'CANCELED DUE TO PAYMENT',
    CANCELED_BY_SYSTEM = 'CANCELED BY SYSTEM'
}