export enum ORDER_STATUS {
    PENDING_REVIEW = 'PENDING REVIEW',
    PENDING_PAYMENT = 'PENDING PAYMENT',
    APPROVED_PAYMENT = 'APPROVED PAYMENT',
    APPROVED = 'APRROVED',
    CONFIRMED_BY_SYSTEM = 'CONFIRMED BY SYSTEM',
    CANCELED_DUE_TO_PAYMENT = 'CANCELED DUE TO PAYMENT',
    CANCELED_BY_SYSTEM = 'CANCELED BY SYSTEM'
}